In [193]:
# https://stackoverflow.com/questions/63714679/plotting-gannt-chart-using-timestamps
# https://towardsdatascience.com/working-with-datetime-in-pandas-dataframe-663f7af6c587

import datetime as dt
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import pandas as pd
import plotly.express as px

report = 'report-1-1-2020.csv'
df = pd.read_csv(report)

df

,Group,Activity type,Duration,From,To,Comment,Group.1,Activity type.1,Duration.1,%
0,NaN,Sleeping,10:28:10,2020-01-01 20:38:54,2020-01-02 7:07:04,NaN,NaN,Computer,11:14:54,45.85
1,NaN,Toilet,0:01:51,2020-01-01 20:36:33,2020-01-01 20:38:24,NaN,Computer,Internet,10:25:28,42.50
2,Computer,Internet,2:19:09,2020-01-01 18:17:20,2020-01-01 20:36:29,NaN,Computer,Movies/TV,0:28:40,1.95
3,Computer,Movies/TV,0:28:40,2020-01-01 17:48:38,2020-01-01 18:17:18,NaN,Computer,Games,0:20:46,1.41
4,NaN,Eating,0:31:50,2020-01-01 17:05:58,2020-01-01 17:37:48,NaN,NaN,Sleeping,7:17:42,29.74
5,Computer,Internet,1:03:40,2020-01-01 16:44:55,2020-01-01 17:48:35,NaN,NaN,Hobby,2:57:21,12.05
6,Housework,Cooking,0:11:09,2020-01-01 16:29:44,2020-01-01 16:40:53,NaN,Hobby,Writing,2:57:21,12.05
7,NaN,Toilet,0:02:11,2020-01-01 16:27:30,2020-01-01 16:29:41,NaN,NaN,Housework,1:32:29,6.28
8,Computer,Internet,1:32:32,2020-01-01 14:54:56,2020-01-01 16:27:28,NaN,Housework,Cleaning,1:21:20,5.53
9,Hobby,Writing,1:39:05,2020-01-01 13:15:47,2020-01-01 14:54:52,NaN,Housework,Cooking,0:11:09,0.76
10,Computer,Games,0:13:07,2020-01-01 13:02:37,2020-01-01 13:15:44,NaN,NaN,Eating,0:31:50,2.16
11,Computer,Internet,0:58:18,2020-01-01 12:04:18,2020-01-01 13:02:36,NaN,NaN,Grooming,0:24:27,1.66
12,Hobby,Writing,1:18:16,2020-01-01 10:45:36,2020-01-01 12:03:52,NaN,NaN,Toilet,0:14:38,0.99
13,Computer,Internet,0:37:25,2020-01-01 10:05:50,2020-01-01 10:43:15,NaN,NaN,NaN,NaN,NaN
14,NaN,Toilet,0:01:10,2020-01-01 10:04:14,2020-01-01 10:05:24,NaN,NaN,NaN,NaN,NaN
15,Computer,Internet,1:11:51,2020-01-01 8:52:21,2020-01-01 10:04:12,NaN,NaN,NaN,NaN,NaN
16,NaN,Toilet,0:02:16,2020-01-01 8:48:34,2020-01-01 8:50:50,NaN,NaN,NaN,NaN,NaN
17,Housework,Cleaning,1:21:20,2020-01-01 7:27:13,2020-01-01 8:48:33,NaN,NaN,NaN,NaN,NaN
18,NaN,Grooming,0:24:27,2020-01-01 6:56:53,2020-01-01 7:21:20,NaN,NaN,NaN,NaN,NaN
19,NaN,Toilet,0:01:38,2020-01-01 6:55:14,2020-01-01 6:56:52,NaN,NaN,NaN,NaN,NaN
20,Computer,Games,0:07:39,2020-01-01 6:45:42,2020-01-01 6:53:21,NaN,NaN,NaN,NaN,NaN
21,Computer,Internet,2:42:33,2020-01-01 4:03:06,2020-01-01 6:45:39,NaN,NaN,NaN,NaN,NaN
22,NaN,Toilet,0:05:32,2020-01-01 3:56:43,2020-01-01 4:02:15,NaN,NaN,NaN,NaN,NaN
23,NaN,Sleeping,4:49:24,2019-12-31 23:07:13,2020-01-01 3:56:37,NaN,NaN,NaN,NaN,NaN

In [238]:
dictionary = csv.DictReader(open(report))
for row in dictionary:
    print(row)

{'Group': '', 'Activity type': 'Computer', 'Duration': '11:14:54', 'From': '2020-01-01 20:38:54', 'To': '2020-01-02 7:07:04', 'Comment': '', '%': '45.85'}
{'Group': 'Computer', 'Activity type': 'Internet', 'Duration': '10:25:28', 'From': '2020-01-01 20:36:33', 'To': '2020-01-01 20:38:24', 'Comment': '', '%': '42.5'}
{'Group': 'Computer', 'Activity type': 'Movies/TV', 'Duration': '0:28:40', 'From': '2020-01-01 18:17:20', 'To': '2020-01-01 20:36:29', 'Comment': '', '%': '1.95'}
{'Group': 'Computer', 'Activity type': 'Games', 'Duration': '0:20:46', 'From': '2020-01-01 17:48:38', 'To': '2020-01-01 18:17:18', 'Comment': '', '%': '1.41'}
{'Group': '', 'Activity type': 'Sleeping', 'Duration': '7:17:42', 'From': '2020-01-01 17:05:58', 'To': '2020-01-01 17:37:48', 'Comment': '', '%': '29.74'}
{'Group': '', 'Activity type': 'Hobby', 'Duration': '2:57:21', 'From': '2020-01-01 16:44:55', 'To': '2020-01-01 17:48:35', 'Comment': '', '%': '12.05'}
{'Group': 'Hobby', 'Activity type': 'Writing', 'Duration': '2:57:21', 'From': '2020-01-01 16:29:44', 'To': '2020-01-01 16:40:53', 'Comment': '', '%': '12.05'}
{'Group': '', 'Activity type': 'Housework', 'Duration': '1:32:29', 'From': '2020-01-01 16:27:30', 'To': '2020-01-01 16:29:41', 'Comment': '', '%': '6.28'}
{'Group': 'Housework', 'Activity type': 'Cleaning', 'Duration': '1:21:20', 'From': '2020-01-01 14:54:56', 'To': '2020-01-01 16:27:28', 'Comment': '', '%': '5.53'}
{'Group': 'Housework', 'Activity type': 'Cooking', 'Duration': '0:11:09', 'From': '2020-01-01 13:15:47', 'To': '2020-01-01 14:54:52', 'Comment': '', '%': '0.76'}
{'Group': '', 'Activity type': 'Eating', 'Duration': '0:31:50', 'From': '2020-01-01 13:02:37', 'To': '2020-01-01 13:15:44', 'Comment': '', '%': '2.16'}
{'Group': '', 'Activity type': 'Grooming', 'Duration': '0:24:27', 'From': '2020-01-01 12:04:18', 'To': '2020-01-01 13:02:36', 'Comment': '', '%': '1.66'}
{'Group': '', 'Activity type': 'Toilet', 'Duration': '0:14:38', 'From': '2020-01-01 10:45:36', 'To': '2020-01-01 12:03:52', 'Comment': '', '%': '0.99'}
{'Group': '', 'Activity type': '', 'Duration': '', 'From': '2020-01-01 10:05:50', 'To': '2020-01-01 10:43:15', 'Comment': '', '%': ''}
{'Group': '', 'Activity type': '', 'Duration': '', 'From': '2020-01-01 10:04:14', 'To': '2020-01-01 10:05:24', 'Comment': '', '%': ''}
{'Group': '', 'Activity type': '', 'Duration': '', 'From': '2020-01-01 8:52:21', 'To': '2020-01-01 10:04:12', 'Comment': '', '%': ''}
{'Group': '', 'Activity type': '', 'Duration': '', 'From': '2020-01-01 8:48:34', 'To': '2020-01-01 8:50:50', 'Comment': '', '%': ''}
{'Group': '', 'Activity type': '', 'Duration': '', 'From': '2020-01-01 7:27:13', 'To': '2020-01-01 8:48:33', 'Comment': '', '%': ''}
{'Group': '', 'Activity type': '', 'Duration': '', 'From': '2020-01-01 6:56:53', 'To': '2020-01-01 7:21:20', 'Comment': '', '%': ''}
{'Group': '', 'Activity type': '', 'Duration': '', 'From': '2020-01-01 6:55:14', 'To': '2020-01-01 6:56:52', 'Comment': '', '%': ''}
{'Group': '', 'Activity type': '', 'Duration': '', 'From': '2020-01-01 6:45:42', 'To': '2020-01-01 6:53:21', 'Comment': '', '%': ''}
{'Group': '', 'Activity type': '', 'Duration': '', 'From': '2020-01-01 4:03:06', 'To': '2020-01-01 6:45:39', 'Comment': '', '%': ''}
{'Group': '', 'Activity type': '', 'Duration': '', 'From': '2020-01-01 3:56:43', 'To': '2020-01-01 4:02:15', 'Comment': '', '%': ''}
{'Group': '', 'Activity type': '', 'Duration': '', 'From': '2019-12-31 23:07:13', 'To': '2020-01-01 3:56:37', 'Comment': '', '%': ''}

In [195]:
start = df['From']
end = df['To']
activity = df['Activity type']
df['Day'] = start.str[0:10]
day = df['Day']
#day = pd.to_datetime(df.From)

In [196]:
day

0     2020-01-01
1     2020-01-01
2     2020-01-01
3     2020-01-01
4     2020-01-01
5     2020-01-01
6     2020-01-01
7     2020-01-01
8     2020-01-01
9     2020-01-01
10    2020-01-01
11    2020-01-01
12    2020-01-01
13    2020-01-01
14    2020-01-01
15    2020-01-01
16    2020-01-01
17    2020-01-01
18    2020-01-01
19    2020-01-01
20    2020-01-01
21    2020-01-01
22    2020-01-01
23    2019-12-31
Name: Day, dtype: object

In [197]:
df['From'] = pd.to_datetime(df.From)
start = df['From']
start

0    2020-01-01 20:38:54
1    2020-01-01 20:36:33
2    2020-01-01 18:17:20
3    2020-01-01 17:48:38
4    2020-01-01 17:05:58
5    2020-01-01 16:44:55
6    2020-01-01 16:29:44
7    2020-01-01 16:27:30
8    2020-01-01 14:54:56
9    2020-01-01 13:15:47
10   2020-01-01 13:02:37
11   2020-01-01 12:04:18
12   2020-01-01 10:45:36
13   2020-01-01 10:05:50
14   2020-01-01 10:04:14
15   2020-01-01 08:52:21
16   2020-01-01 08:48:34
17   2020-01-01 07:27:13
18   2020-01-01 06:56:53
19   2020-01-01 06:55:14
20   2020-01-01 06:45:42
21   2020-01-01 04:03:06
22   2020-01-01 03:56:43
23   2019-12-31 23:07:13
Name: From, dtype: datetime64[ns]

In [198]:
df['To'] = pd.to_datetime(df.To)
end = df['To']
end

0    2020-01-02 07:07:04
1    2020-01-01 20:38:24
2    2020-01-01 20:36:29
3    2020-01-01 18:17:18
4    2020-01-01 17:37:48
5    2020-01-01 17:48:35
6    2020-01-01 16:40:53
7    2020-01-01 16:29:41
8    2020-01-01 16:27:28
9    2020-01-01 14:54:52
10   2020-01-01 13:15:44
11   2020-01-01 13:02:36
12   2020-01-01 12:03:52
13   2020-01-01 10:43:15
14   2020-01-01 10:05:24
15   2020-01-01 10:04:12
16   2020-01-01 08:50:50
17   2020-01-01 08:48:33
18   2020-01-01 07:21:20
19   2020-01-01 06:56:52
20   2020-01-01 06:53:21
21   2020-01-01 06:45:39
22   2020-01-01 04:02:15
23   2020-01-01 03:56:37
Name: To, dtype: datetime64[ns]

In [270]:
new_df = pd.DataFrame([
    dict(Start='2019-12-31 23:07:13', End='2020-01-01 3:56:37', Day="1/1/2020", Activity="Sleeping"),
    dict(Start='2020-01-01 3:56:43', End='2020-01-01 4:02:15', Day="1/1/2020", Activity="Toilet"),
    dict(Start='2020-01-01 4:03:06', End='2020-01-01 6:45:39', Day="1/1/2020", Activity="Internet"),
    dict(Start='2020-01-01 6:56:53', End='2020-01-01 7:21:20', Day="1/1/2020", Activity="Grooming"),
    dict(Start='2020-01-01 7:27:13	', End='2020-01-01 8:48:33	', Day="1/1/2020", Activity="Cleaning"),
    dict(Start='2020-01-01 8:52:21	', End='2020-01-01 10:04:12	', Day="1/1/2020", Activity="Internet"),
    dict(Start='2020-01-01 10:45:36	', End='2020-01-01 12:03:52	', Day="1/1/2020", Activity="Writing"),
    dict(Start='2020-01-01 20:38:54	', End='2020-01-02 7:07:04	', Day="1/1/2020", Activity="Sleeping"),

    #dict(Start=start, End=end, Day=day, Activity=activity),
])

fig = px.timeline(new_df, x_start="Start", x_end="End", y='Day', color="Activity"
                 )

# you can manually set the range as well
fig.update_layout(xaxis=dict(
                      title='Timestamp', 
                      tickformat = '%H:%M:%S',
                      range = ['2020-01-01 00:00:00','2020-01-01 24:00:00']
                  ))
fig.show()

ValueError: 'NoneType' object is not subscriptable

Invalid value received for the 'range' property of layout.xaxis

    The 'range' property is an info array that may be specified as:

    * a list or tuple of 2 elements where:
(0) The 'range[0]' property accepts values of any type
(1) The 'range[1]' property accepts values of any type

Property does not support subscripting:
range_x
^^^^^